saml:
  idp-issuer-uri: ${saml-idp-issuer-uri}
  idp-public-cert: ${saml-idp-public-cert}
  idp-public-key: ${saml-idp-public-key}
  sp-entity-id: ${saml-sp-entity-id}
  sp-redirect-callback: ${saml-sp-redirect-callback}
  sp-redirect-logout: ${saml-sp-redirect-logout}


